sudo: false
dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - 4
  - 6
matrix:
  fast_finish: true
env:
  global:
    - CXX=g++-4.8
script: npm run travis
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - sqlite3
      - gdal-bin
before_install:
  - npm i -g npm@^3.0.0
  - sqlite3 --version
before_script:
  - npm prune
after_success:
  - npm run semantic-release
