sudo: false
dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - 4
  - 6
matrix:
  fast_finish: true
script: npm run travis
addons:
  apt:
    packages:
      - gdal-bin
      - proj-bin
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
