sudo: required
services:
  - docker
dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - 4
  - 6
matrix:
  fast_finish: true
script:
  - docker build -t pelias/interpolation .
  - docker run pelias/interpolation npm run travis
after_success:
  - docker run pelias/interpolation npm run semantic-release
